platform :ios, '7.0' 

target 'MyVideo' do
pod 'SDWebImage'
pod 'AFNetworking'
pod 'MJRefresh'
pod 'SVProgressHUD'
pod 'JSONModel'
pod 'Masonry'
pod 'FMDB'
pod 'Google-Mobile-Ads-SDK'
pod 'UMengAnalytics'
pod 'XHVersion'
end
